In [ ]:
#importing pandas
import pandas as pd

In [ ]:
#reading csv file
df=pd.read_csv("/customer_shopping_behavior.csv")

In [ ]:
#displaying the data
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
#displaying a brief information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
#describing the summary of the  data
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
#describing the summary of the data including alphanumerical data
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [ ]:
#checking for missing values for each column int he dataset
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
#filling up the missing values in review rating based on each cateogry
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [ ]:
#checking for missing values after replacing it with the median
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
#converting the column names lower case and replacing spaces with underscore(_)
df.columns= df.columns.str.lower()
df.columns= df.columns.str.replace(" ","_")
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [ ]:
#checking the column names
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
#creating a new column "age_group" to classify customers into different age groups
labels=["Young Adult","Adult","Middle Aged","Senior"]
df["age_group"]=pd.qcut(df["age"],q=4,labels=labels)

In [ ]:
#displaying the age an age group column together
df[["age","age_group"]].head(15)

    age    age_group
0    55  Middle Aged
1    19  Young Adult
2    50  Middle Aged
3    21  Young Adult
4    45  Middle Aged
5    46  Middle Aged
6    63       Senior
7    27  Young Adult
8    26  Young Adult
9    57  Middle Aged
10   53  Middle Aged
11   30  Young Adult
12   61       Senior
13   65       Senior
14   64       Senior

In [ ]:
#creating new column named "frequency_purchase_days" to show the frequency of purchases in number of days

#creating a dictionary to contain all the value types from the column "frequency of purchases"
frequency_mapping= {"Fortnightly":14,
                    "Weekly":7,
                    "Annually":365,
                    "Monthly":30,
                    "Quarterly":90,
                    "Bi-Weekly":14,
                    "Every 3 Months":90}
df["frequency_purchase_days"]=df["frequency_of_purchases"].map(frequency_mapping)

In [ ]:
#displaying the new column with the old column "frequency_pf_purchases"
df[["frequency_of_purchases","frequency_purchase_days"]].head(20)

   frequency_of_purchases  frequency_purchase_days
0             Fortnightly                       14
1             Fortnightly                       14
2                  Weekly                        7
3                  Weekly                        7
4                Annually                      365
5                  Weekly                        7
6               Quarterly                       90
7                  Weekly                        7
8                Annually                      365
9               Quarterly                       90
10              Bi-Weekly                       14
11            Fortnightly                       14
12            Fortnightly                       14
13                 Weekly                        7
14                 Weekly                        7
15                Monthly                       30
16              Bi-Weekly                       14
17              Quarterly                       90
18                 Weekly                        7
19              Bi-Weekly                       14

In [ ]:
#checking if the columns "promo_code_used" and "discount_applied" have the same value in each entry
#if same then dropping any one of the column
df[["discount_applied","promo_code_used"]].head(10)
(df["discount_applied"]==df["promo_code_used"]).all()

np.True_

In [ ]:
#removing the column "promo_code_used" since the values of the two columns are same
df=df.drop('promo_code_used',axis=1)
#displaying the list of columns in the dataset
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'frequency_purchase_days'],
      dtype='object')

In [ ]:
#install sql modules
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.12)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [ ]:
from sqlalchemy import create_engine

#Connecting to Neon SQL Database
# Your Neon database string
neon_connection_string = "postgresql+psycopg2://neondb_owner:npg_W3KlPvmI7BtT@ep-restless-waterfall-aolphya0.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"

engine = create_engine(neon_connection_string, pool_pre_ping=True)

table_name = "customer_data"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into the cloud database!")

Data successfully loaded into the cloud database!

It appears the PostgreSQL server is not running or accessible from your Colab environment. Connecting to `localhost` for a PostgreSQL server isn't typically feasible in Google Colab as `localhost` refers to the Colab runtime itself, which doesn't host a PostgreSQL server by default.

As an alternative, I'll demonstrate how to load your DataFrame into an **in-memory SQLite database**, which is a lightweight and self-contained database that works well within the Colab environment without requiring external server setup. If you intend to connect to an external PostgreSQL database, you would need to provide its accessible host/IP address and ensure it's running.